spring.application.name=expensetracker-backend

# DATABASE - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

# SERVER
server.port=8080

# LOGGING
logging.level.com.backend.expensetracker_backend=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG

# AUTH0 - OAuth2 Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-mk00wdmgz5nn6d2c.us.auth0.com/
#spring.security.oauth2.resourceserver.jwt.audiences=https://securescan.com/api/v2/
spring.security.oauth2.resourceserver.jwt.audiences=vZIz3FyY3q1kbk0Jj18JI1PDTfGd3bdX

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000